// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BmuDzdvBvjmpurED6_Dvk4doxuy8Q4s',
    appId: '1:549196747541:web:ecd055c9273c26f729cf1c',
    messagingSenderId: '549196747541',
    projectId: 'evently-app-f2c7a',
    authDomain: 'evently-app-f2c7a.firebaseapp.com',
    storageBucket: 'evently-app-f2c7a.firebasestorage.app',
    measurementId: 'G-YE0DDFCSBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbProf2kx7ADv4aiptFLEQvmrwwB1fBhs',
    appId: '1:549196747541:android:07bc18fc7c749bd429cf1c',
    messagingSenderId: '549196747541',
    projectId: 'evently-app-f2c7a',
    storageBucket: 'evently-app-f2c7a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-hrTc7OwRgQ50lag2SxKOf6339CFo9Lk',
    appId: '1:549196747541:ios:0f68f738e4fcaf5d29cf1c',
    messagingSenderId: '549196747541',
    projectId: 'evently-app-f2c7a',
    storageBucket: 'evently-app-f2c7a.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-hrTc7OwRgQ50lag2SxKOf6339CFo9Lk',
    appId: '1:549196747541:ios:0f68f738e4fcaf5d29cf1c',
    messagingSenderId: '549196747541',
    projectId: 'evently-app-f2c7a',
    storageBucket: 'evently-app-f2c7a.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BmuDzdvBvjmpurED6_Dvk4doxuy8Q4s',
    appId: '1:549196747541:web:af1686f40ecee63129cf1c',
    messagingSenderId: '549196747541',
    projectId: 'evently-app-f2c7a',
    authDomain: 'evently-app-f2c7a.firebaseapp.com',
    storageBucket: 'evently-app-f2c7a.firebasestorage.app',
    measurementId: 'G-YY6CHZBN7S',
  );
}
